// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddToCartInput struct {
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
	UserID    string `json:"userId"`
}

type CartItem struct {
	ID        string   `json:"id"`
	ProductID string   `json:"productId"`
	Product   *Product `json:"product"`
	Quantity  int      `json:"quantity"`
	UserID    string   `json:"userId"`
}

type CreateOrderInput struct {
	UserID string            `json:"userId"`
	Items  []*OrderItemInput `json:"items"`
}

type CreateProductInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	Category    string  `json:"category"`
	SellerID    string  `json:"sellerId"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Mutation struct {
}

type Order struct {
	ID        string       `json:"id"`
	UserID    string       `json:"userId"`
	User      *User        `json:"user"`
	Items     []*OrderItem `json:"items"`
	Total     float64      `json:"total"`
	Status    OrderStatus  `json:"status"`
	CreatedAt string       `json:"createdAt"`
}

type OrderItem struct {
	ID        string   `json:"id"`
	ProductID string   `json:"productId"`
	Product   *Product `json:"product"`
	Quantity  int      `json:"quantity"`
	Price     float64  `json:"price"`
}

type OrderItemInput struct {
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	Category    string  `json:"category"`
	SellerID    string  `json:"sellerId"`
	Seller      *User   `json:"seller"`
	CreatedAt   string  `json:"createdAt"`
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
}
