// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AddToCartInput struct {
	CarID    string `json:"carId"`
	Quantity int    `json:"quantity"`
}

type CarFilterInput struct {
	Brand        *string           `json:"brand,omitempty"`
	Model        *string           `json:"model,omitempty"`
	MinYear      *int              `json:"minYear,omitempty"`
	MaxYear      *int              `json:"maxYear,omitempty"`
	MinPrice     *float64          `json:"minPrice,omitempty"`
	MaxPrice     *float64          `json:"maxPrice,omitempty"`
	MinMileage   *int              `json:"minMileage,omitempty"`
	MaxMileage   *int              `json:"maxMileage,omitempty"`
	FuelType     *FuelType         `json:"fuelType,omitempty"`
	Transmission *TransmissionType `json:"transmission,omitempty"`
	City         *string           `json:"city,omitempty"`
	State        *string           `json:"state,omitempty"`
}

type CarInput struct {
	Title        string           `json:"title"`
	Description  string           `json:"description"`
	Brand        string           `json:"brand"`
	Model        string           `json:"model"`
	Year         int              `json:"year"`
	Price        float64          `json:"price"`
	Mileage      int              `json:"mileage"`
	Color        string           `json:"color"`
	FuelType     FuelType         `json:"fuelType"`
	Transmission TransmissionType `json:"transmission"`
	Images       []string         `json:"images"`
	Location     *LocationInput   `json:"location"`
	Features     []string         `json:"features"`
	SellerName   string           `json:"sellerName"`
	SellerEmail  string           `json:"sellerEmail"`
	SellerPhone  string           `json:"sellerPhone"`
}

type CarsResponse struct {
	Cars       []*Car `json:"cars"`
	Total      int    `json:"total"`
	Page       int    `json:"page"`
	Limit      int    `json:"limit"`
	TotalPages int    `json:"totalPages"`
}

type LocationInput struct {
	City    string   `json:"city"`
	State   string   `json:"state"`
	Country string   `json:"country"`
	Lat     *float64 `json:"lat,omitempty"`
	Lng     *float64 `json:"lng,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateCarInput struct {
	ID           string            `json:"id"`
	Title        *string           `json:"title,omitempty"`
	Description  *string           `json:"description,omitempty"`
	Brand        *string           `json:"brand,omitempty"`
	Model        *string           `json:"model,omitempty"`
	Year         *int              `json:"year,omitempty"`
	Price        *float64          `json:"price,omitempty"`
	Mileage      *int              `json:"mileage,omitempty"`
	Color        *string           `json:"color,omitempty"`
	FuelType     *FuelType         `json:"fuelType,omitempty"`
	Transmission *TransmissionType `json:"transmission,omitempty"`
	Status       *CarStatus        `json:"status,omitempty"`
	Images       []string          `json:"images,omitempty"`
	Location     *LocationInput    `json:"location,omitempty"`
	Features     []string          `json:"features,omitempty"`
}

type UpdateUserInput struct {
	Name   *string `json:"name,omitempty"`
	Email  *string `json:"email,omitempty"`
	Phone  *string `json:"phone,omitempty"`
	Avatar *string `json:"avatar,omitempty"`
}
